server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 50
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** #搜索微服务
    user-service: /user/** #用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 授权中心微服务
    order-service: /order/** # 订单微服务
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers:  #配置禁止使用的头信息，这里设置为null，否则set-cookie无效
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
leyou:
  jwt:
    pubKeyPath:  D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth/accredit
      - /api/auth/verify
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/query
      - /api/user/code
      - /api/item
      - /api/cart